### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by rmcgibbo** [inorton/cclash#15]
I see a couple errors with "Illegal characters in path". Whatever the path is works fine with msvc, and still still works just fine using cclash (except for the error message), although I presume that no caching is happening -- so I don't think the underlying cl.exe actually cares about these illegal characters.

Example:
```
[ 29%] Building C object test/driver_stub/CMakeFiles/OpenCLDriverStub.dir/cl.c.obj
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at CClash.Compiler.ProcessArguments(String[] args) in c:\Users\inb\Desktop\cclash\cclash\CClash\Compiler.cs:line 554
```

**Comment by inorton** [comment]
Hiya. C# is a little more strict (and flexible) about path formation, particularly as it supports multiple platforms. It is complaining because on windows "/" isn't truly the path separator. I feel your pain!

Where we employ cclash we have another program responsible for sorting out the paths from cygwin form into windows form before calling the compiler.

We could build in a crude convertor to swap the separator in Compiler.c in the ProcessArguments method but I think it might need alot of testing beforehand.

**Comment by inorton** [comment]
As it happens I'm just writing that crude / -> \ converter now :)
